# --- CORE SETTINGS ---

# log all dns queries, uncomment to enable debugging
# log-queries
# send to stderr instead of syslog
log-facility=-

# Ignore the host machine's /etc/resolv.conf
no-resolv

# set ttl so that if this server goes down, devices can still resolve the hosts using their local cache
local-ttl=86400

# Cache size (defaults to 150). 1000 is a good baseline for a modern home network.
cache-size=1000

# use router as default name server
server=<routerIpHere>

# --- PRIVACY & LEAK PREVENTION ---

# Never forward plain names (without a dot or domain part) upstream
domain-needed

# Never forward requests for private IP ranges (192.168.x.x, 10.x.x.x) upstream
bogus-priv

# Explicitly define your local domain. 
# This guarantees that ANY query ending in .apps.lan is resolved locally 
# or fails locally, and is NEVER sent to upstream
local=/lan/

# --- LOCAL RECORDS ---
# Explicit host-IP mappings
address=/dns.infra.lan/<serverIpHere>
address=/docker.infra.lan/<serverIpHere>
address=/dev.infra.lan/<serverIpHere>
address=/ha.apps.lan/<serverIpHere>
address=/alarm.apps.lan/<serverIpHere>
